language: ruby

sudo: false

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.0

gemfile:
  - test/gemfiles/prawn-2.1
  - test/gemfiles/prawn-2.2

script: bundle exec rake test

branches:
  only:
    - master
    - /\-stable$/
