language: ruby

sudo: false

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - test/gemfiles/prawn-2.1
  - test/gemfiles/prawn-2.2

before_install:
  - travis_retry gem update --system

script: bundle exec rake test
